# Generated by Django 3.2.16 on 2023-03-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('ProfileImg', models.ImageField(upload_to='Images')),
                ('EmailId', models.CharField(max_length=50)),
                ('PhoneNumber', models.IntegerField()),
                ('Address', models.TextField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('Username', models.TextField(max_length=20, unique=True)),
                ('Password', models.TextField(max_length=20)),
            ],
        ),
    ]
