# Generated by Django 3.2.16 on 2023-03-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogTitle', models.TextField(max_length=50)),
                ('BlogImg', models.ImageField(upload_to='Images')),
                ('BlogCategoryID', models.IntegerField()),
                ('BlogContent', models.TextField()),
                ('BlogSummery', models.TextField()),
                ('BlogStatus', models.BooleanField(default=True)),
                ('RegistrationID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogCategoryName', models.CharField(max_length=50)),
            ],
        ),
    ]
