# Generated by Django 3.2.16 on 2023-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_blog_blogcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogStatus',
            field=models.IntegerField(),
        ),
    ]
