# Generated by Django 3.2.16 on 2023-03-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_blog_blogstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField()),
                ('RequiredSpeciality', models.CharField(max_length=50)),
                ('AppointmentDate', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('RegistrationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.registration')),
            ],
        ),
    ]
